- Obtener el nombre del alumno y el nombre de la clase en la que está inscrito.
- Obtener el nombre del alumno y la materia de las clases en las que está inscrito.
- Obtener el nombre del alumno, la edad y el nombre del profesor de las clases en las que está inscrito.
- Obtener el nombre del alumno y la dirección de las clases en las que está inscrito.
- Obtener el nombre del alumno y el nombre de la clase junto con el profesor.
- Obtener el nombre del alumno, la materia y el nombre del profesor de las clases en las que está inscrito.
- Obtener el nombre del alumno, la edad y la materia de las clases en las que está inscrito.
- Obtener el nombre del alumno, la dirección y el profesor de las clases en las que está inscrito.
- Obtener el nombre del alumno y la materia de las clases en las que está inscrito, ordenado por el nombre del alumno.
- Contar cuántos alumnos están inscritos en cada clase.
